apiVersion: v1
kind: Secret
metadata:
  name: webrtc-app-secrets
  namespace: laravel-webrtc
type: Opaque
stringData:
  APP_KEY: ""
  DB_USERNAME: "webrtc"
  DB_PASSWORD: "secret"
  DB_ROOT_PASSWORD: "supersecret"
  PSTN_PROVIDER_TOKEN: "mock-token"
  PSTN_MOCK_TOKEN: "mock-token"
